version: '3'
services:
  web:
    volumes:
      - ".:/usr/src/app"
    build: .
    ports:
      - "3001:3001"
  db:
    image: postgres
    volumes:
      - db-data:/Users/maxparker/Desktop/APIs/finance/db/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=restapi
      - POSTGRES_PASSWORD=""
      - POSTGRES_DATABASE=SQL-dw-dev

volumes:
  db-data:
