version: '3'
services:
  web:
    volumes:
      - ".:/usr/src/app"
    build: .
    ports:
      - "3001:3001"
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=restapi
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=demodb
